// Generated by CoffeeScript 1.6.2
(function() {
  var User, config, db, mongoose, userSchema;

  config = require('../../config/config.js');

  mongoose = require('mongoose');

  mongoose.connect(config.mongogodb_uri);

  userSchema = mongoose.Schema({
    username: String,
    displayName: String,
    talkingIn: {
      items: [
        {
          id: String,
          objectType: String
        }
      ],
      totalItems: Number
    }
  });

  User = mongoose.model('User', userSchema);

  exports.User = User;

  db = mongoose.connection;

  db.on('error', console.error.bind(console, 'connection error:'));

  db.once('open', function() {
    return console.log('Mongo connected');
  });

}).call(this);
